# This is a TOML document. Boom.

# needle(pic) max size
NeedleMaxSize  = 10485760

# max batch upload 
BatchMaxNum    = 9

[Store]
# volume meta index
VolumeIndex      = "C:\\Users\\Administrator.DESKTOP-DTQSFP1\\Desktop\\project\\kitten\\tmp\\volume.idx"

# free volume meta index
FreeVolumeIndex  = "C:\\Users\\Administrator.DESKTOP-DTQSFP1\\Desktop\\project\\kitten\\tmp\\free_volume.idx"

[Volume]
# sync delete operation after N delete
SyncDelete  = 1024

# sync delete delay duration
SyncDeleteDelay  = "10s"

[Block]
# sync write operation after N write
SyncWrite      = 1

# use new kernel syscall syncfilerange
Syncfilerange  = true

[Index]
# index bufio size
BufferSize = 4096

# merge delay duration
MergeDelay  =  "10s"

# merge write after N write
MergeWrite  = 1024

# ring buffer cache
RingBuffer  = 10240

# sync write operation after N write
SyncWrite   = 1024

# use new kernel syscall syncfilerange
Syncfilerange = true
